[#ftl]
[@b.head/]
[@b.toolbar title="个人资料维护"]bar.addBack();[/@]
 [#assign user=teacher.user/]
    [@b.form action=sa theme="list" action=b.rest.save(profile) enctype="multipart/form-data"]
      [@b.field label="账户"]${user.code} ${user.name} ${user.department.name}[/@]
      [@b.select label="所在院系" name="user.department.id" items=departs value=teacher.user.department required="true"/]
      [@b.select label="职称" name="teacher.title.id" items=titles value=teacher.title!  /]
      [@b.select label="学位" name="teacher.degree.id" items=degrees value=teacher.degree! /]
      [@b.select label="学历" name="teacher.educationDegree.id" items=eduDegrees value=teacher.educationDegree! /]
      [@b.textarea label="个人简介" name="profile.intro" value=(profile.intro)! cols="100" rows="10" required="true" maxlength="500" comment="500字以内"/]
      [@b.textarea label="教学经历" name="profile.teachingCareer" value=profile.teachingCareer!  cols="100" rows="10" maxlength="500" comment="500字以内"/]
      [@b.textarea label="研究方向" name="profile.research" value=profile.research! cols="100" rows="3" maxlength="100" comment="100字以内"/]
      [@b.textarea label="科研成果" name="profile.harvest" value=profile.harvest!  cols="100" rows="10" maxlength="500" comment="500字以内"/]
      [@b.textarea label="学术兼职" name="profile.titles" value=profile.titles!  cols="100" rows="10" maxlength="500" comment="500字以内"/]
      [@b.textarea label="联系信息" name="profile.contact" placeholder="办公室电话、地址、电子邮箱等" value=profile.contact! cols="100" rows="3" comment="100字以内"/]
      [@b.formfoot]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
    [/@]
[@b.foot/]