[#ftl]
[@b.head/]
[@b.toolbar title="教师简介维护"]bar.addBack();[/@]
 [#assign user=teacher.user/]
[@b.form action=sa action=b.rest.save(profile) theme="list" enctype="multipart/form-data"]
  [@b.field label="工号"]${profile.teacher.user.code}[/@]
  [@b.field label="姓名"]${profile.teacher.user.name}[/@]
  [@b.select label="教学院系" name="teacher.department.id" items=departs value=teacher.department required="true"/]
  [@b.select label="职称" name="teacher.title.id" items=titles value=teacher.title!  /]
  [@b.select label="学位" name="teacher.degree.id" items=degrees value=teacher.degree! /]
  [@b.select label="学历" name="teacher.educationDegree.id" items=eduDegrees value=teacher.educationDegree! /]
  [@b.textarea label="个人简介" name="profile.intro" value=(profile.intro)! cols="80" rows="10" required="true" maxlength="5000"/]
  [@b.textarea label="教学经历" name="profile.teachingCareer" value=profile.teachingCareer!  cols="80" rows="5" maxlength="5000" comment="500字以内"/]
  [@b.textarea label="研究方向" name="profile.research" value=(profile.research)! cols="80" rows="2"/]
  [@b.textarea label="科研成果" name="profile.harvest" value=(profile.harvest)!  cols="80" rows="6" maxlength="5000"/]
  [@b.textarea label="学术兼职" name="profile.titles" value=profile.titles!  cols="80" rows="5" maxlength="5000" comment="500字以内"/]
  [@b.textarea label="联系方式" name="profile.contact" value=(profile.contact)! cols="80" rows="2"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[@b.foot/]