[#ftl]
[@b.head/]
[@b.grid items=profiles var="profile"]
  [@b.gridbar]
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="teacher.user.code" title="工号"/]
    [@b.col width="10%" property="teacher.user.name" title="姓名"][@b.a href="!info?id=${profile.id}"]${profile.teacher.user.name}[/@][/@]
    [@b.col width="18%" property="teacher.user.department.name" title="部门"/]
    [@b.col width="17%" property="teacher.title.name" title="职称"/]
    [@b.col width="20%" property="teacher.degree.name" title="学位"/]
    [@b.col width="20%" property="teacher.educationDegree.name" title="学历"/]
  [/@]
[/@]
[@b.foot/]
